# singleNode is a boolean that determines if the cluster will be created with 1 replica
# Set to true if Lucenia cluster config discovery.type is set to single-node
# If true, the cluster will be created with 1 replica by default
# If false, the cluster will be created the replicaCount number of nodes
singleNode: true

# config is used to add configuration such as `lucenia.yml` and `log4j2.properties`
config:
  lucenia.yml: |
    cluster.name: lucenia-cluster

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
    # Implicitly done if ".singleNode" is set to "true".
    discovery.type: single-node

    # Start Lucenia Security Demo Configuration
    # WARNING: revise all the lines below before you go into production
    plugins:
      license:
        certificate: |
          --------BEGIN LICENSE CERTIFICATE-------
          ID: 625d793f-dacb-4e54-a8b1-8c0a54f55dbd
          Type: Trial License
          Licensee: Lucenia Skylite CI
          Expiry: 2025-03-27

          8A6D5A32 3F1CC159 17DA4B94 E5AD60C6
          140F4CA0 E1DFE53B AD92251F A2D88614
          C3E8EF69 F23C3FA3 0723C90C 175CB562
          5743D7DB 4AABF9AA A0E1C3EE E9B8DDA0
          20C84189 C254EE78 FC6C4B4C C57F7134
          8544E09D 1F129962 2D20C526 2F07A064
          800C8D41 20765394 80CF6D79 90638336
          7BDDD980 9CA11B57 2F7646D2 1EE08E71
          --------END LICENSE CERTIFICATE---------
      security:
        ssl:
          transport:
            pemcert_filepath: node.pem
            pemkey_filepath: node-key.pem
            pemtrustedcas_filepath: root-ca.pem
            enforce_hostname_verification: false
          http:
            enabled: true
            pemcert_filepath: node.pem
            pemkey_filepath: node-key.pem
            pemtrustedcas_filepath: root-ca.pem
        allow_unsafe_democertificates: true
        allow_default_init_securityindex: true
        authcz:
          admin_dn:
            - CN=kirk,OU=client,O=client,L=test,C=de
        audit.type: internal_lucenia
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: false
          indices:
            [
              # define list of indices that are managed by security
            ]
    ######## End Lucenia Security Demo Configuration ########
  # log4j2.properties:

# extraEnvs are additional environment variables to set for  the nodeGroup
# Will be appended to the current 'env:' key. You can use any kubernetes env syntax
extraEnvs:
  - name: LUCENIA_INITIAL_ADMIN_PASSWORD
    value: myStrongPassword123!
