{{- $root := . }}
{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lucenia.uname" . }}-config
  labels:
    {{- include "lucenia.labels" . | nindent 4 }}
data:
{{- range $configName, $configYaml := .Values.config }}
  {{ $configName }}: |
    {{- if (eq (kindOf $configYaml) "map")}}
    {{-   tpl (toYaml $configYaml) $root | nindent 4 }}
    {{- else -}}
    {{-   tpl $configYaml $root | nindent 4 }}
    {{- end -}}
{{- end -}}
{{- end -}}
