# See https://github.com/helm/chart-testing-action
name: Lint and Test Charts

on: [pull_request, workflow_dispatch]

env:
  CI_VALUES_FILE: ${{ secrets.CI_VALUES_FILE }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: ["1.25.2", "1.26.15", "1.27.16"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Repo Secret CI_VALUES_FILE as charts/lucenia/ci/test-values.yaml
        run: echo "${{ secrets.CI_VALUES_FILE }}" > charts/lucenia/ci/test-values.yaml

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "CHART_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:v${{ matrix.k8s }}
          kubectl_version: v${{ matrix.k8s }}
        if: ${{ env.CHART_CHANGED == 'true' }}

      # See https://github.com/helm/chart-testing/blob/main/doc/ct_install.md
      - name: Run chart-testing (install)
        run: ct install --config ct.yaml --debug
