name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!charts/**/ci/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Prepare GPG Key
        run: |
          echo "${{ secrets.RELEASE_SECRET }}" | gpg --dearmor --output keyring.gpg
          echo "${{ secrets.RELEASE_PHRASE }}" > passphrase-file.txt

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      # See: https://github.com/helm/chart-releaser
      # See: https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_KEY: Lucenia Dev (RELEASE SIGNING KEY) <dev@lucenia.io>
          CR_KEYRING: keyring.gpg
          CR_PASSPHRASE_FILE: passphrase-file.txt
          CR_SIGN: true
          CR_TOKEN: "${{ secrets.HELM_CHART_RELEASE_TOKEN }}"
